spring.application.name=meeting-intelligence
spring.profiles.active=local

//logging
logging.level.root=${LOG_LEVEL:INFO}
logging.level.org.springframework.web=INFO
logging.level.com.yourpackage=DEBUG

spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3309}/${DATABASE_NAME:meeting_intelligence}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

//swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

//jwt
jwt.secret=ThisIsMyVerySecretKeyForMeetingIntelligenceSystem2026
jwt.expiration=86400000

//groq
groq.api.key=${GROQ_API_KEY}
groq.url=https://api.groq.com/openai/v1/chat/completions
